language: go
go: 
- 1.1
- tip
script:
  - sudo add-apt-repository --yes ppa:chris-lea/node.js
  - sudo apt-get install node
  - sudo npm install -g bower
  - pushd web; make; popd
  - go list -f '{{range .XTestImports}}{{.}}{{"\n"}}{{end}}' | xargs go get
  - go test ./...
